version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/web/Dockerfile
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - .:/app:z
  mongodb:
    image: mongo
