version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app:/app:z
